### ISSUE TITLE
Follow Us social plugin

### ISSUE THREAD

**Issue by sponsonby** [dominioncross/dcross#13]
Paste the follow code on the Ascent homepage right before the close body tag to invite prospects to follow us on social media. 

< script >
  var _gscq = _gscq || [];
  _gscq.push(['language', navigator.language]);
  (function() {
    var gscw = document.createElement('script');
    gscw.type = 'text/javascript'; gscw.async = true;
    gscw.src = '//widgets.getsitecontrol.com/14690/script.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gscw, s);
  })();
< /script >

**Comment by benpetro** [comment]
CURRENT GOOGLE ANALYTICS STATS:

01/03/15 - 30/03/15
Bounce Rate: 49.88%
Sessions: 6832
Pageviews: 28172
