### ISSUE TITLE
Cancel Ecom Transaction/Discount Code

### ISSUE THREAD

**Issue by sponsonby** [dominioncross/dcross#14]
Discount code did not apply on to transaction - (Not sure if it was a bug or oversight) Order number 10001504. Can you please void and refund the transaction and Stuart will re-submit it with the order.

**Comment by benpetro** [comment]
It was oversight ;)

**Comment by benpetro** [comment]
Card processed for $108.18, fix invoice to show discount of 71.77 and total of 108.18

**Comment by sponsonby** [comment]
Can you please send me a copy of the revised invoice. I just had Paul from Stay Safe querying the error.
