### ISSUE TITLE
Wholesale REPORT

### ISSUE THREAD

**Issue by lbevis** [dominioncross/dcross#16]
Total Indents by Style

Getting very different numbers between 'total indent by style' and 'pallet, bts, jan drop by style  & size profile'

The 'pallet, bts, jan etc etc etc' report seems correct.

http://dx.dxforklift.com/wholesale/reports/options?report=indents_orders

**Comment by lbevis** [comment]
BP, please fix this report tomorrow (thurs) require for ordering to factories. Thanks

**Comment by lbevis** [comment]
Major indent is also providing incorrect data:

Scholar D Snr (pallet/jan/bts) = 3,803prs on 
http://dx.dxforklift.com/wholesale/reports/options?report=orders_style_size

Scholar D Snr (pallet/jan/bts) =1,191prs on major indent
http://dx.dxforklift.com/wholesale/reports/options?report=major_indent

**Comment by benpetro** [comment]
On it now...
