### ISSUE TITLE
HR Calendar (Print Option)

### ISSUE THREAD

**Issue by lbevis** [dominioncross/dcross#6]
We need a fortnightly summary for Sheila that is printer friendly.  To date Sheila has printed the calendar however if there are more than two events on the day, those extra events are being missed.

Sheila enters date period required and a summary of who was away, what type of leave and how many hours.

http://dx.dxforklift.com/hr/events

**Comment by benpetro** [comment]
Can't she just print the List?

http://dxforklift.com/hr/events/list

**Comment by benpetro** [comment]
I've fixed the searching of the list, so I think this issue is fixed
